version: '3'

services:
  web:
    build: diplom_django
    command: bash -c "cd /app && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .\diplom_django:/app
    ports:
      - 8080:8000
