version: '3.5'

services:

  db:
    container_name: db
    user: root
    ports:
      - '5432:5432'
    
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: admin
      POSTGRES_DB: db
      PGDATA: postgres/data
      POSTGRES_INITDB_ARGS: "-A md5"

    image: postgres:14.3

    volumes:
      - ./postgres/data:/postgres/data