version: '3'

services:
  worker:
    build: worker
    stop_grace_period: 5s
    deploy:
      update_config:
        failure_action: rollback
    labels:
      - "auto_remove=true"
    volumes:
      - media:/app/media
  
  web:
    build: diplom_django
    environment:
      - DJANGO_SUPERUSER_USERNAME=admin
      - DJANGO_SUPERUSER_PASSWORD=admin
      - DJANGO_SUPERUSER_EMAIL=kurwabober@example.com
    command: >
      bash -c "
      python3 run.py"
    volumes:
      - ./diplom_django:/app 
      - //var/run/docker.sock:/var/run/docker.sock
      - media:/app/furniture_monitoring/media
    ports:
      - 8080:8000
    depends_on:
      - db

  redis:
    image: redis
    ports:
      - "6379:6379"
      
  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=db
    ports:
      - 5432:5432
    # volumes:
    #   - postgres_data:/var/lib/postgresql/data/

  event_handler:
    build: event_handler 
    volumes:
      - ./event_handler:/app 
    depends_on:
      - redis
    links:
      - redis
    command: >
      bash -c "
      python3 main.py"

volumes:
  postgres_data:
  media:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./diplom_django/furniture_monitoring/media
