version: '3'

services:
  # worker:
  #   build: worker
  #   command: bash
  #   stdin_open: true
  #   tty: true
  #   volumes:
  #     - ./worker:/app
  #   depends_on:
  #     - redis
  #   links:
  #     - redis
  #   deploy:
  #     resources:
  #       reservations:
  #         devices:
  #           - driver: nvidia
  #             count: 1
  #             capabilities: [gpu]
              
  worker:
    build: worker
  web:
    build: diplom_django
    environment:
      - DJANGO_SUPERUSER_USERNAME=admin
      - DJANGO_SUPERUSER_PASSWORD=admin
      - DJANGO_SUPERUSER_EMAIL=kurwabober@example.com
    command: >
      bash -c "
      python3 run.py"
    volumes:
      - ./diplom_django:/app
    ports:
      - 8080:8000
    depends_on:
      - db

  redis:
    image: redis
    ports:
      - "6379:6379"
      
  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  event_handler:
    build: event_handler 
    stdin_open: true
    tty: true
    volumes:
      - ./event_handler:/app 
    depends_on:
      - redis
    links:
      - redis
volumes:
  postgres_data:
