# Generated by Django 5.0.4 on 2024-05-13 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furniture_monitoring', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='linecounter',
            name='coord_left',
        ),
        migrations.RemoveField(
            model_name='linecounter',
            name='coord_right',
        ),
        migrations.AddField(
            model_name='linecounter',
            name='end_x',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='linecounter',
            name='end_y',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='linecounter',
            name='start_x',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='linecounter',
            name='start_y',
            field=models.FloatField(default=0),
        ),
    ]
