# Generated by Django 5.0.4 on 2024-05-22 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furniture_monitoring', '0003_remove_linecounter_event_history_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='video_path',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
